### PR TITLE
Liquid/[Increment|Decrement]

### PR DESCRIPTION
**Pull request by fbernier**
So I started playing with this and figured I'd try adding something to wrap my head around the codebase. I guess there could be some work done to avoid duplication, but I am not completely sure what I did is right. 

I am not familiar with Liquid (yet) but I guess some more work will have to be done on the erb_compiler. If so, I'd be happy to do it with some guidance. Hopefully this is going to be useful in some ways.

### CODE REVIEW

**Comment by gmalette** [comment]
I'm not sure what @sgnr 's take is on this; I'm not sure if they should be part of the language or just regular tags

**Comment by gmalette** [comment]
Otherwise code LGTM, missing the compiler part if you're up for it

**Comment by sgnr** [comment]
As @gmalette said, it should be a plain tag and not part of the grammar. #19 that was merged today is the first step to have custom tags but that is not supported quite yet. If you are interested, I can notify you when custom tags are supported so you may edit and resubmit your PR.

**Comment by fbernier** [comment]
Makes sense. Yes I'd be glad to rework it as tags instead.

**Comment by gmalette** [comment]
First tag implementation #23

**Comment by fbernier** [comment]
:ok_hand: Will look into this asap

**Pull request closed without merging**
